# Generated by Django 5.2.16 on 2026-09-15 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0019_drop_llm_cost_accounting'),
        ('integrations', '0008_encrypted_column_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='transcription_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transcribing_agents', to='integrations.integration'),
        ),
    ]
