# Generated by Django 5.2.16 on 2026-09-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0020_aiagent_transcription_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='transcription_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
