# Generated by Django 5.2.16 on 2026-09-14 21:32

import chatballs.conversations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0024_queue_policy_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.FileField(blank=True, default='', max_length=512, upload_to=chatballs.conversations.models.contact_avatar_upload_path),
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar_content_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar_source',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
