# Generated by Django 5.2.16 on 2026-09-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0025_contact_avatar_contact_avatar_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_turn_state',
            field=models.CharField(choices=[('NONE', 'Ход не нужен'), ('PENDING', 'Ожидает'), ('RUNNING', 'Считается'), ('DONE', 'Отвечено'), ('FAILED', 'Не удалось')], default='NONE', max_length=8),
        ),
    ]
