# Generated by Django 5.2.17 on 2026-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0026_message_external_transport_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_failure_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('', 'Не задано'), ('queued', 'В очереди'), ('provider_accepted', 'Принято провайдером'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка доставки'), ('no_account', 'Аккаунт не найден')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='gateway_command_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
