# Generated by Django 5.2.17 on 2026-09-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0026_message_ai_turn_state'),
        ('conversations', '0027_message_delivery_status'),
    ]

    operations = [
    ]
