/** Public CSS hooks. Keep this registry as the single list for widget help. */
export const widgetClasses = {
  root: "cb-widget",
  header: "cb-header",
  headerIcon: "cb-header-icon",
  headerTitle: "cb-header-title",
  headerButton: "cb-header-button",
  body: "cb-body",
  message: "cb-message",
  messageClient: "cb-message--client",
  messageContent: "cb-message-content",
  bubble: "cb-bubble",
  bubbleClient: "cb-bubble--client",
  bubbleAgent: "cb-bubble--agent",
  bubbleOperator: "cb-bubble--operator",
  bubbleAudio: "cb-bubble--audio",
  messageTime: "cb-message-time",
  composer: "cb-composer",
  composerInput: "cb-composer-input",
  composerButton: "cb-composer-button",
  sendButton: "cb-send-button",
  recordButton: "cb-record-button",
  startFooter: "cb-start-footer",
  startButton: "cb-start-button",
  form: "cb-form",
  formField: "cb-form-field",
  formSubmit: "cb-form-submit",
  brand: "cb-brand",
} as const;
